reminder form done
jennyeong/health-companion pull request #9
Opened 2022-08-31 10:53 UTC by danyyaw

2022-08-31 12:09 UTC, jennyeong commented on app/controllers/reminders_controller.rb
> +      format.html { redirect_to reminders_url, notice: "Reminder was successfully destroyed." }
Instead of "Reminder was successfully destroyed", can help to change the wording to "Reminder was successfully deleted" --> More user friendly.

2022-08-31 12:14 UTC, jennyeong commented on app/models/reminder.rb
> +  belongs_to :medicine
I think Reminder shouldnt belongs_to medicine, more of has_one medicine

2022-09-03 01:16 UTC, jennyeong requested changes

2022-09-03 01:16 UTC, jennyeong commented on app/models/reminder.rb
> +  belongs_to :medicine
```suggestion
  has_one :medicine
```

2022-09-03 01:24 UTC, danyyaw reviewed
Changes done

2022-09-03 01:24 UTC, danyyaw commented on app/controllers/reminders_controller.rb
> +      format.html { redirect_to reminders_url, notice: "Reminder was successfully destroyed." }
```suggestion
      format.html { redirect_to reminders_url, notice: "Reminder was successfully deleted." }
```

2022-09-03 01:28 UTC, merged